name: lows_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  url_launcher: ^6.3.0
  flutter_pdfview: ^1.3.2

flutter:
  uses-material-design: true


  assets:
    - assets/
